handler: aime
dataset_path: yentinglin/aime_2025
dataset_subset: default
dataset_split: train
question_key: problem
answer_key: answer
templating_parameters:
  template: "{prompt}\nReturn your final response within \\boxed{{}}"