### model
model_name_or_path: Qwen/QwQ-32B

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: AStarThought
template: qwen
cutoff_len: 16384
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ../res/model/AStarThought-QwQ-32B
logging_steps: 1
save_strategy: epoch
plot_loss: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0
warmup_ratio: 0.1
lr_scheduler_type: cosine
seed: 42
bf16: true

report_to: wandb
run_name: A*-Thought